import * as stylex from '@stylexjs/stylex';

export const cardStyles = stylex.create({
  container: {
    cursor: 'pointer',
    display: 'flex',
    height: 380,
    perspective: '1000px',
    padding: 0,
    '@media (max-width: 767px)': { height: 280 },
  },
  flipCard: {
    height: 350,
    position: 'relative',
    transformStyle: 'preserve-3d',
    width: 250,
    '@media (max-width: 767px)': { height: 250, width: 150 },
  },
  front: {
    backfaceVisibility: 'hidden',
    height: '100%',
    position: 'absolute',
    transform: 'rotateY(0deg)',
    width: '100%',
    zIndex: 2,
  },
  image: {
    borderRadius: 8,
    boxShadow: '0 25px 100px -10px rgba(169, 154, 154, 0.54)',
    height: 350,
    width: 250,
    '@media (max-width: 767px)': { height: 250, width: 150 },
  },
  back: {
    backfaceVisibility: 'hidden',
    borderRadius: 8,
    height: '100%',
    position: 'absolute',
    transform: 'rotateY(180deg)',
    width: '100%',
    zIndex: 3,
  },
  backContainer: {
    alignItems: 'center',
    backgroundColor: 'var(--theme-primary-light, #81c784)',
    borderRadius: 8,
    color: 'var(--theme-button-text, #fff)',
    display: 'flex',
    flexDirection: 'column',
    height: 350,
    justifyContent: 'center',
    overflow: 'visible',
    padding: 6,
    position: 'relative',
    width: 250,
    '@media (max-width: 767px)': { height: 250, width: 150 },
  },
  title: {
    display: 'flex',
    fontSize: '0.8rem',
    justifyContent: 'center',
    marginTop: 2,
    '@media (max-width: 767px)': { fontSize: '0.7rem' },
  },
  overview: {
    display: 'flex',
    fontSize: '0.7rem',
    justifyContent: 'center',
    lineHeight: 1.5,
    '@media (max-width: 767px)': {
      WebkitBoxOrient: 'vertical',
      WebkitLineClamp: 5,
      display: '-webkit-box',
      fontSize: '0.5rem',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
  },
  score: {
    color: 'var(--score-color)',
    display: 'flex',
    justifyContent: 'center',
  },
  scoreContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    marginBottom: 0,
    marginTop: 'auto',
  },
  addButton: {
    backgroundColor: 'var(--theme-white, #fff)',
    borderColor: 'var(--theme-primary, #4caf50)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    color: 'var(--theme-black, #000)',
    cursor: 'pointer',
    fontSize: '1rem',
    height: 40,
    marginBottom: 4,
    marginLeft: 'auto',
    marginRight: 'auto',
    paddingBlock: 6,
    paddingInline: 16,
    width: 140,
    '@media (max-width: 767px)': {
      fontSize: '0.7rem',
      height: 30,
      width: 100,
    },
  },
  addedButton: {
    backgroundColor: 'var(--theme-black, #000)',
    color: 'var(--theme-white, #fff)',
    cursor: 'not-allowed',
  },
});
