import * as stylex from '@stylexjs/stylex';

export const detailsStyles = stylex.create({
  backButton: {
    backgroundColor: 'var(--theme-primary-light, #81c784)',
    borderColor: 'var(--theme-primary, #4caf50)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    color: 'var(--theme-button-text, #fff)',
    cursor: 'pointer',
    fontSize: '1rem',
    marginBottom: 8,
    paddingBlock: 6,
    paddingInline: 16,
    transition: 'background 0.2s',
    ':hover': { backgroundColor: 'var(--theme-primary, #4caf50)' },
    '@media (max-width: 767px)': {
      fontSize: '0.7rem',
      paddingInline: 10,
    },
  },
  container: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    marginInline: 'auto',
    minHeight: '100vh',
    padding: 18,
    '@media (max-width: 1024px)': { padding: 8 },
    '@media (max-width: 767px)': { padding: 4 },
  },
  posterImage: {
    borderRadius: 6,
    marginTop: 8,
    width: 300,
    '@media (max-width: 1024px)': { width: 220 },
    '@media (max-width: 767px)': { width: 140 },
  },
  detailFlex: {
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: 8,
  },
  infoColumnsWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    '@media (max-width: 767px)': { alignItems: 'center', width: '100%' },
  },
  infoColumn: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    lineHeight: 1.5,
    minWidth: 0,
    padding: 6,
    '@media (max-width: 992px)': { padding: 4 },
    '@media (max-width: 767px)': { fontSize: '0.8rem', padding: 2 },
  },
  infoText: { fontSize: '1rem', margin: 2 },
  infoLabel: { fontWeight: 'bold', marginRight: 2 },
  castSection: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 16,
  },
  castList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
    marginBottom: 16,
  },
  imageColumn: { alignItems: 'center', display: 'flex', flexDirection: 'column' },
  tagline: {
    color: 'var(--theme-primary-light, #81c784)',
    marginInline: 'auto',
    marginTop: 6,
    textAlign: 'center',
    width: 300,
    wordBreak: 'break-word',
    '@media (max-width: 767px)': { fontSize: '0.8rem' },
  },
  mainColumns: {
    alignItems: 'flex-start',
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    '@media (max-width: 1024px)': { gap: 4 },
    '@media (max-width: 767px)': {
      alignItems: 'center',
      flexDirection: 'column',
      gap: 4,
    },
  },
  leftColumn: { alignItems: 'center', display: 'flex', flexDirection: 'column' },
  rightColumn: {
    alignItems: 'flex-start',
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
  },
  title: {
    alignItems: 'center',
    color: 'var(--theme-primary-light, #81c784)',
    fontSize: '1.5rem',
    marginBlock: 6,
    marginInline: 'auto',
    textAlign: 'center',
    width: 300,
    wordBreak: 'break-word',
    '@media (max-width: 1024px)': { fontSize: '1.25rem', width: 220 },
    '@media (max-width: 767px)': { fontSize: '1rem', width: 140 },
  },
  castCard: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
    width: 120,
    '@media (max-width: 1024px)': { width: 90 },
    '@media (max-width: 767px)': { width: 60 },
  },
  castImage: {
    alignItems: 'center',
    backgroundColor: 'var(--theme-button-text, #fff)',
    borderRadius: 6,
    display: 'flex',
    height: 120,
    justifyContent: 'center',
    objectFit: 'cover',
    width: 80,
    '@media (max-width: 1024px)': { height: 90, width: 60 },
    '@media (max-width: 767px)': { height: 60, width: 40 },
  },
  castName: {
    color: 'var(--theme-primary-light, #81c784)',
    fontWeight: 'bold',
    marginTop: 4,
    '@media (max-width: 767px)': { fontSize: '0.8rem' },
  },
  castCharacter: {
    fontSize: '0.8rem',
    '@media (max-width: 767px)': { fontSize: '0.7rem' },
  },
  castImageFallback: {
    alignItems: 'center',
    backgroundColor: 'var(--theme-white, #fff)',
    borderRadius: 6,
    color: 'var(--theme-primary, #4caf50)',
    display: 'flex',
    fontSize: '0.8rem',
    height: 120,
    justifyContent: 'center',
    width: 80,
    '@media (max-width: 1024px)': { fontSize: '0.7rem', height: 90, width: 60 },
    '@media (max-width: 767px)': { fontSize: '0.5rem', height: 60, width: 40 },
  },
  posterContainer: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  buttonContainer: { display: 'flex', gap: 8, marginBottom: 8 },
});
