import * as stylex from '@stylexjs/stylex';

export const navbarStyles = stylex.create({
  brandWrapper: { alignItems: 'center', display: 'flex' },
  navbar: {
    alignItems: 'center',
    backgroundColor: 'var(--theme-black, #000)',
    display: 'flex',
    justifyContent: 'center',
    paddingBlock: 4,
    position: 'sticky',
    top: 0,
    width: '100%',
    zIndex: 1000,
    '@media (max-width: 992px)': {
      justifyContent: 'space-between',
      padding: 4,
      position: 'relative',
    },
  },
  navList: {
    display: 'flex',
    justifyContent: 'center',
    listStyle: 'none',
    margin: 0,
    padding: 0,
    '@media (max-width: 992px)': {
      alignItems: 'flex-start',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'none',
      flexDirection: 'column',
      paddingBottom: 8,
      position: 'absolute',
      top: '100%',
      zIndex: 100,
    },
  },
  navListOpen: { '@media (max-width: 992px)': { display: 'flex' } },
  navItem: {
    color: 'var(--theme-primary-light, #81c784)',
    fontSize: '1.25rem',
    padding: 20,
    whiteSpace: 'nowrap',
    '@media (max-width: 1200px)': { fontSize: '1rem', padding: 18 },
    '@media (max-width: 1024px)': { fontSize: '1rem', padding: 16 },
    '@media (max-width: 992px)': { fontSize: '0.8rem', padding: 2 },
    '@media (max-width: 767px)': { fontSize: '0.5rem', padding: 2 },
    ':hover': {
      textDecorationLine: 'underline',
      textDecorationThickness: '5px',
    },
  },
  navItemActive: {
    color: 'var(--theme-white, #fff)',
    textDecorationLine: 'underline',
    textDecorationThickness: '5px',
  },
  link: { color: 'inherit', textDecoration: 'none' },
  hamburger: {
    display: 'none',
    '@media (max-width: 992px)': {
      backgroundColor: 'transparent',
      borderColor: 'var(--theme-primary-light, #81c784)',
      borderStyle: 'solid',
      borderWidth: 1,
      color: 'var(--theme-primary-light, #81c784)',
      cursor: 'pointer',
      display: 'block',
      fontSize: '1.5rem',
      marginLeft: 'auto',
      paddingRight: 8,
    },
  },
  brand: {
    alignItems: 'center',
    color: 'var(--theme-primary-light, #81c784)',
    display: 'flex',
    fontSize: '1.5rem',
    listStyle: 'none',
    marginRight: 'auto',
    paddingLeft: 20,
    '@media (max-width: 1200px)': { fontSize: '1.25rem', paddingLeft: 18 },
    '@media (max-width: 1024px)': { fontSize: '1rem', paddingLeft: 16 },
    '@media (max-width: 992px)': { fontSize: '0.8rem', marginRight: 0, paddingLeft: 4 },
    '@media (max-width: 767px)': { fontSize: '0.7rem', paddingLeft: 2 },
  },
  themeButton: {
    backgroundColor: 'var(--theme-primary, #4caf50)',
    borderColor: 'var(--theme-primary-light, #81c784)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    color: 'var(--theme-button-text, #fff)',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    marginLeft: 'auto',
    minWidth: 120,
    padding: 8,
    ':hover': { backgroundColor: 'var(--theme-primary-light, #81c784)' },
    '@media (max-width: 1200px)': { margin: 4 },
    '@media (max-width: 992px)': { margin: 2, padding: 6 },
    '@media (max-width: 767px)': { margin: 4, padding: 4 },
  },
});
