import * as stylex from '@stylexjs/stylex';

export const movieStyles = stylex.create({
  flexWrapper: {
    alignItems: 'flex-start',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 20,
    justifyContent: 'center',
    marginTop: 32,
  },
  rowContainer: { position: 'relative' },
  rowTitle: {
    color: 'var(--theme-primary-light, #81c784)',
    fontSize: '1.5rem',
    marginBottom: 8,
    marginLeft: 8,
    '@media (max-width: 1200px)': { fontSize: '1.25rem' },
    '@media (max-width: 992px)': { fontSize: '1rem' },
  },
  cardsViewport: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginInline: 'auto',
    overflow: 'hidden',
  },
  cardsWrapper: {
    display: 'flex',
    gap: 16,
    opacity: 0,
    transition: 'opacity 0.2s ease-out',
  },
  cardsReady: { opacity: 1 },
  arrow: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderColor: 'var(--theme-primary, #4caf50)',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    color: 'var(--theme-primary, #4caf50)',
    cursor: 'pointer',
    fontSize: '2rem',
    height: 64,
    opacity: 0.3,
    pointerEvents: 'auto',
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    transition: 'opacity 0.2s, background-color 0.2s',
    width: 48,
    zIndex: 2,
    ':hover': {
      backgroundColor: 'var(--theme-primary-light, #81c784)',
      color: 'var(--theme-button-text, #fff)',
      opacity: 1,
    },
    ':focus': {
      outline: '2px solid var(--theme-primary-light, #81c784)',
      outlineOffset: 2,
      opacity: 1,
    },
    ':focus:not(:focus-visible)': { outline: 'none' },
    ':focus-visible': {
      outline: '2px solid var(--theme-primary-light, #81c784)',
      outlineOffset: 2,
      opacity: 1,
    },
    ':disabled': { cursor: 'not-allowed', opacity: 0.1 },
  },
  arrowActive: { opacity: 1 },
  arrowLeft: {
    left: '-2rem',
    '@media (max-width: 1200px)': { left: '-1.5rem' },
    '@media (max-width: 1024px)': { left: '-1.2rem' },
    '@media (max-width: 992px)': { left: '-1rem' },
    '@media (max-width: 767px)': { left: 0 },
  },
  arrowRight: {
    right: '-1.5rem',
    '@media (max-width: 1200px)': { right: '-1.5rem' },
    '@media (max-width: 1024px)': { right: '-1.2rem' },
    '@media (max-width: 992px)': { right: '-1rem' },
    '@media (max-width: 767px)': { right: 0 },
  },
  cardWrapper: { position: 'relative' },
});
