import Head from 'next/head';

const MainIndex = () => {
  return (
    <div>
      <Head>
        <title>Netflix-clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export default MainIndex;
