import './globals.css';
import { Poppins } from 'next/font/google';

export const metadata = {
  title: 'Netflix clone',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${poppins.className}`}>{children}</body>
    </html>
  );
}
